### ISSUE TITLE
有bug, 

### ISSUE THREAD

**Issue by aviggngyv** [zongphp/html#1]
你的Html.php里少了use zongphp\html\build\Base;

**Comment by aviggngyv** [comment]
不过还是谢谢你精简那个后盾网的库, 那家伙搞一堆依赖,还是老师呢,哼

**Comment by zongphp** [comment]
哈哈，居然有人用啊，后盾那个的确是太多依赖，我也是用不爽就自己精简改了。但主要还是自己学习使用github、composer、packagist。这个项目应该不会再更新的了，建议你还是使用后盾，支持原创。
